### ISSUE TITLE
compile with issue

### ISSUE THREAD

**Issue by radioman1511** [hvanruys/EUMETCastView#1]
C:\EUMETCastView-1.1.9\meteosatlib\Compress.h:39: Fehler: CDataField.h: No such file or directory

**Comment by hvanruys** [comment]
You need the Public Wavelet Transform Decompression Library Software
and a registration .... see http://www.eumetsat.int/website/home/Data/DataDelivery/SupportSoftwareandTools/index.html

**Comment by probonopd** [comment]
Having the same issue. So this software cannot be compiled without signing up providing a real name and address?

http://www.eumetsat.int/website/home/Data/DataDelivery/SupportSoftwareandTools/index.html says:

>  It is a licensed software and only available upon acceptance of the WaveLet Transform Software Licence, which will be presented to you as part of the electronic registration process.

What are the license terms? Is there an open source replacement?

References:
* https://github.com/probonopd/EUMETCastView/blob/patch-1/.travis.yml
* https://travis-ci.org/probonopd/EUMETCastView/jobs/324178085#L654
