### ISSUE TITLE
EUMETCastView .dll missing

### ISSUE THREAD

**Issue by SimoneAv** [hvanruys/EUMETCastView#6]
All, I am trying to run EUMETCastView on Windows 10 machine. After downloading and unzipping the EUMETCastView_Windows_64bit_v1.5.6 file, I am running the EUMETCastView.exe file. I then get the following errors for some .dll missing:

The code execution cannot proceed because libfreeimage-3.dll was not found. Reinstalling the program may fix this problem.
The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem.
The code execution cannot proceed because libarchive-13.dll was not found. Reinstalling the program may fix this problem.
The code execution cannot proceed because libgcc_s_seh-1.dll was not found. Reinstalling the program may fix this problem.

Would you be able to provide further information and or assistance on the above?

Regards

**Comment by sq7r0** [comment]
run .bat file instead
